version: "3.3"

# use already network
networks: 
  default:
    external:
      name: proxy


services:
  traefik:
    container_name: tk
    restart: always
    image: traefik:latest
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    # labels: 
    #   - traefik.frontend.rule=Host:monitor.example.com
    #   - traefik.port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/traefik.toml
      - $PWD/acme.json.toml:/acme.json
    networks: 
      - default

