#https://github.com/mustafaileri/redis-cluster-with-sentinel
version: '3'
services:
  master:
    image: redis:4.0.6-alpine
    command: redis-server --requirepass foobared
    # build not recommanded maybe because conf image
    # build:
      # context: ./redis-master/
    #scale range of port 
    ports: 
      - 16379-26370:6379
    deploy:
      mode: replicated
      replicas: 6
  slave:
    image: redis:4.0.6-alpine
    command: redis-server --slaveof redis-master 6379 --masterauth foobared
    # command: redis-server --slaveof redis-master 6379 
    # build:
      # context: ./redis-slave/
    #scale port with "+"
    ports:
      - 26379-36370:6379
    links:
      - master:redis-master
  sentinel:
    build: sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    links:
      - master:redis-master
      - slave