version: '3'

networks:
  app-tier:
    driver: bridge
services:
  redis-master:
    image: 'bitnami/redis:latest'
    ports:
      - '4001:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=my_master_password
    volumes:
      - '/path/to/redis-persistence:/bitnami'
    networks:
      - app-tier

  redis-slave:
    image: 'bitnami/redis:latest'
    ports:
      - '4002:6379'
    networks:
      - app-tier
    # depends_on:
    #   - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-primary
      - REDIS_MASTER_PORT_NUMBER=4001
      - REDIS_MASTER_PASSWORD=my_master_password
      - REDIS_PASSWORD=my_slave_password