FROM cassandra:3.11

ENV CASSANDRA_LISTEN_ADDRESS 127.0.0.1
ENV CASSANDRA_CLUSTER_NAME "cha-cluster"
ENV JVM_OPTS "-Xms512m -Xmx512m"
# VOLUME [ "/home/dd/workdata/docker-work/Cassandra/Tuto/data", "/var/lib/cassandra"]
